version: 2.1

# Reusable command to handle ZIP file processing
commands:
  process_zip:
    parameters:
      zip_file:
        type: string
    steps:
      - checkout

      # Install necessary tools
      - run:
          name: Install AWS CLI and unzip
          command: |
            if ! command -v aws &> /dev/null; then
              pip install awscli
            fi
            sudo apt-get update && sudo apt-get install -y unzip

      # Configure AWS CLI
      - run:
          name: Configure AWS CLI
          command: |
            mkdir -p ~/.aws
            echo "[default]" > ~/.aws/config
            echo "region = us-east-1" >> ~/.aws/config
            echo "[default]" > ~/.aws/credentials
            echo "aws_access_key_id = ${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
            echo "aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials

      # Download, unzip, and upload to S3
      - run:
          name: Process and upload ZIP file
          command: |
            mkdir -p tmp
            cd tmp
            ZIP_FILE=<< parameters.zip_file >>
            aws s3 cp "s3://htwordpressbucket/$ZIP_FILE" . --endpoint-url https://eu2.contabostorage.com
            unzip "$ZIP_FILE"
            rm "$ZIP_FILE"
            
            # Extract the year from the ZIP file name
            YEAR=$(echo "$ZIP_FILE" | grep -oE '^(202[0-4])' | head -n 1 || echo "unknown")
            if [ "$YEAR" = "unknown" ]; then
              echo "Unable to determine the destination folder. Skipping upload."
              exit 1
            fi
            
            # Upload to the determined S3 folder
            aws s3 cp . "s3://htwordpressbucket/$YEAR/" --recursive --endpoint-url https://eu2.contabostorage.com
            cd ..
            rm -rf tmp

# Define jobs for each ZIP file
jobs:
  upload_zip_2020_11:
    docker:
      - image: circleci/python:3.8
    steps:
      - process_zip:
          zip_file: "2020 11.zip"

  upload_zip_202020_09:
    docker:
      - image: circleci/python:3.8
    steps:
      - process_zip:
          zip_file: "202020 09.zip"

  upload_zip_2021_07:
    docker:
      - image: circleci/python:3.8
    steps:
      - process_zip:
          zip_file: "2021 07.zip"

  upload_zip_2021_09:
    docker:
      - image: circleci/python:3.8
    steps:
      - process_zip:
          zip_file: "2021 09.zip"

  upload_zip_2021_11:
    docker:
      - image: circleci/python:3.8
    steps:
      - process_zip:
          zip_file: "2021 11.zip"

  upload_zip_2022_01:
    docker:
      - image: circleci/python:3.8
    steps:
      - process_zip:
          zip_file: "2022 01.zip"

  upload_zip_2022_03:
    docker:
      - image: circleci/python:3.8
    steps:
      - process_zip:
          zip_file: "2022 03.zip"

  upload_zip_2022_05:
    docker:
      - image: circleci/python:3.8
    steps:
      - process_zip:
          zip_file: "2022 05.zip"

  upload_zip_2022_07:
    docker:
      - image: circleci/python:3.8
    steps:
      - process_zip:
          zip_file: "2022 07.zip"

  upload_zip_2022_09:
    docker:
      - image: circleci/python:3.8
    steps:
      - process_zip:
          zip_file: "2022 09.zip"

  upload_zip_2022_11:
    docker:
      - image: circleci/python:3.8
    steps:
      - process_zip:
          zip_file: "2022 11.zip"

  upload_zip_2023_03_1:
    docker:
      - image: circleci/python:3.8
    steps:
      - process_zip:
          zip_file: "2023 03 (1).zip"

  upload_zip_2023_05:
    docker:
      - image: circleci/python:3.8
    steps:
      - process_zip:
          zip_file: "2023 05.zip"

  upload_zip_2023_07:
    docker:
      - image: circleci/python:3.8
    steps:
      - process_zip:
          zip_file: "2023 07.zip"

  upload_zip_2023_09:
    docker:
      - image: circleci/python:3.8
    steps:
      - process_zip:
          zip_file: "2023 09.zip"

  upload_zip_2023_11:
    docker:
      - image: circleci/python:3.8
    steps:
      - process_zip:
          zip_file: "2023 11.zip"

  upload_zip_2024:
    docker:
      - image: circleci/python:3.8
    steps:
      - process_zip:
          zip_file: "2024.zip"

  upload_zip_OIP_1:
    docker:
      - image: circleci/python:3.8
    steps:
      - process_zip:
          zip_file: "OIP (1).zip"

  upload_zip_aioseo:
    docker:
      - image: circleci/python:3.8
    steps:
      - process_zip:
          zip_file: "aioseo.zip"

  upload_zip_htaccess:
    docker:
      - image: circleci/python:3.8
    steps:
      - process_zip:
          zip_file: "htaccess.zip"

workflows:
  version: 2
  upload_workflow:
    jobs:
      - upload_zip_2020_11:
          context: test
      - upload_zip_202020_09:
          context: test
      - upload_zip_2021_07:
          context: test
      - upload_zip_2021_09:
          context: test
      - upload_zip_2021_11:
          context: test
      - upload_zip_2022_01:
          context: test
      - upload_zip_2022_03:
          context: test
      - upload_zip_2022_05:
          context: test
      - upload_zip_2022_07:
          context: test
      - upload_zip_2022_09:
          context: test
      - upload_zip_2022_11:
          context: test
      - upload_zip_2023_03_1:
          context: test
      - upload_zip_2023_05:
          context: test
      - upload_zip_2023_07:
          context: test
      - upload_zip_2023_09:
          context: test
      - upload_zip_2023_11:
          context: test
      - upload_zip_2024:
          context: test
      - upload_zip_OIP_1:
          context: test
      - upload_zip_aioseo:
          context: test
      - upload_zip_htaccess:
          context: test
